version: '3.6'

services:
  db:
    image: postgres:10.4
    restart: always
    volumes:
      - type: volume
        source: ./database
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # command: python3 manage.py runsslserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./mysite:/app
    ports:
      - "25000:8000"
    depends_on:
      - db

  redis:
    container_name: 'redis'
    image: 'redis:4.0.11-stretch'
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  database:
  redisdata: