version: '3.6'

services:
  db:
    image: postgres:10.4

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/app
    ports:
      - "8000:8000"
    depends_on:
      - db